### ISSUE TITLE
Add simple "current situation" file with only the latest values per each location.

### ISSUE THREAD

**Issue by cipriancraciun** [cipriancraciun/covid19-datasets#12]
From: https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-607536652
> Unfortunately it looks way too complex for my needs and like I said, I'm looking for something very simple aka: countryName, totalCases, totalDeceased and totalRecovered.

From: https://github.com/CSSEGISandData/COVID-19/issues/1281#issuecomment-607541154
> Thought I would submit a request here if I may.
> Is there any way to create a simple JSON dataset along the lines of, for example
> "country": "Australia"
> "cases": 4860
> "deaths": 20
> "recovered": 244

**Comment by cipriancraciun** [comment]
@ChrisParkerWA I am thinking about adding a new file that contains only the following values:
* the location information (country, province, administrative);
* the latest date, and the number of days since first case, 10 cases, 100 cases, 1k cases and 10k cases, and days since peak;  (it could be useful to display on a dashboard how "far" a country is in the pandemic;)
* the latest cumulative confirmed, recovered, deaths and infected;
* the delta from the previous day, and the percentage since the peak;  (again can be used to assess the current situation;)

Would this solve your issue?  Is this still to complex?  (You can just ignore some values.)

**Comment by ChrisParkerWA** [comment]
**@cipriancraciun** 
That sounds like a great idea. Would that file be accessible via a URL that I could use to download from?

**Comment by cipriancraciun** [comment]
@ChrisParkerWA certainly it will be accessible both via GitHub (and you can use the "raw" URL, which unfortunately will require redirects), but also I'll upload it (as with the other files) **on the "web" so it can be downloaded without issues**.

It'll be ready in an hour or so.

**Comment by ChrisParkerWA** [comment]
**@cipriancraciun** 
That would be superb.  I guess like most of us around the world, you would be in some kind of lockdown too.  Very few of us alive have ever experienced anything like this.  2020 will be a year to forget.

**Comment by cipriancraciun** [comment]
OK, I've uploaded in each `exports` folders (except `combined`) a `status.json` file that holds only the latest data as discussed above.

The `status.json` is structured so that if ones loads it in a JSON object in JavaScript, one can easily access his interested location as:
~~~~
var _status = /* load `status.json` */;
var _us = _status.countries["United States"];
~~~~

----

The files are available in the GitHub repository at:
* https://github.com/cipriancraciun/covid19-datasets/blob/master/exports/jhu/v1/status.json
* https://github.com/cipriancraciun/covid19-datasets/blob/master/exports/jhu/v1/daily/status.json
* https://github.com/cipriancraciun/covid19-datasets/blob/master/exports/jhu/v1/series/status.json
* https://github.com/cipriancraciun/covid19-datasets/blob/master/exports/nytimes/v1/us-states/status.json
* https://github.com/cipriancraciun/covid19-datasets/blob/master/exports/nytimes/v1/us-counties/status.json
* https://github.com/cipriancraciun/covid19-datasets/blob/master/exports/ecdc/v1/worldwide/status.json

To download them from GitHub use the `View raw` or `Raw` button and use that link (but notice that it does redirect).  (Alternatively see bellow for the files published directly on the "web".)

----

These files are also available at:
* https://scratchpad.volution.ro/ciprian/eedf5eb117ec363ca4f88492b48dbcd3/exports/jhu/v1/status.json
* https://scratchpad.volution.ro/ciprian/eedf5eb117ec363ca4f88492b48dbcd3/exports/jhu/v1/series/status.json
* https://scratchpad.volution.ro/ciprian/eedf5eb117ec363ca4f88492b48dbcd3/exports/jhu/v1/daily/status.json
* https://scratchpad.volution.ro/ciprian/eedf5eb117ec363ca4f88492b48dbcd3/exports/nytimes/v1/us-states/status.json
https://scratchpad.volution.ro/ciprian/eedf5eb117ec363ca4f88492b48dbcd3/exports/nytimes/v1/us-counties/status.json
https://scratchpad.volution.ro/ciprian/eedf5eb117ec363ca4f88492b48dbcd3/exports/ecdc/v1/worldwide/status.json

**Comment by cipriancraciun** [comment]
@ChrisParkerWA, when you get time to look at the status file, let me know if it works for you, or if there are any other issues or changes that you think should be made.

**Comment by ChrisParkerWA** [comment]
**@cipriancraciun** 
Thank you for creating that.  It's going to take me a while to get my head around it so I'll get back to you.  I'm no expert in JSON so this is quite a challenge.

**Comment by cipriancraciun** [comment]
@ChrisParkerWA how do you intend to use it?  (I could help you with a snippet of code.)

**Comment by ChrisParkerWA** [comment]
**@cipriancraciun** 
I wrote an iOS App for my own use as an exercise in gaining practise in SwiftUI (Xcode).  It displays the status of the pandemic for each country and provides a global total at the top. It also has sorting options to sort by country (ascending), cases (descending), deaths (descending) and recovered (descending).  If you look at my github repo for the App you can see a screen capture
https://github.com/ChrisParkerWA/CovidStatus
So essentially the only fields I require are country name, cases, deaths and infected.  I assume I can derive recovered from cases - (deaths + infected)

**Comment by cipriancraciun** [comment]
@ChrisParkerWA so, the you can take the following approach:
* load the `status.json` (perhaps from the JHU dataset, or ECDC depending on which you want);
* I assume it is loaded in a variable such as `_data` which is a hash-map;
* from that select the world-wide data as `_data["world"]["World"]` which has the same schema as a "country record";
* for each country, start with `_data["countries"]` (which is a hash-map with keys the country name), then iterate only on the values (ignoring the keys);  these records are also a "country record";
* now for each "country record", which I assume you have in a variable named `_country`, you can extract the following:
* `_country_name = _country["location"]["country"]`  (in case of the total world-wide data this equals with `World`;)
* `_country_confirmed = _country["values"]["absolute"]["confirmed"]`;
* the same for `_country_deaths`, `_country_recovered` and `_country_infected`;  (**also check these values for `null`**, which happens in case there are no reported figures for that particular country;)
* (as you see the recovered field is already computed and present in the dataset;  however note that the `recovered` and `infected` values can be unreliable as stated by JHU;)

**Comment by ChrisParkerWA** [comment]
**@cipriancraciun** 
Thank you.  I appreciate the effort you've gone to in order to help me out.  I'll see how I go.
