### ISSUE TITLE
Also export the TSV data per individual country

### ISSUE THREAD

**Issue by cipriancraciun** [cipriancraciun/covid19-datasets#31]
On the JHU repository someone asked if it would be possible to make it easier for one to find only a particular country's data:
* https://github.com/CSSEGISandData/COVID-19/issues/2065

Therefore perhaps an export (only for the country level, and in case of US up to state level) for each individual country would be a good idea.

**Comment by cipriancraciun** [comment]
@Dan-74 I've added the following exports:
* https://github.com/cipriancraciun/covid19-datasets/tree/master/exports/jhu/v1/daily-by-country
* https://github.com/cipriancraciun/covid19-datasets/tree/master/exports/jhu/v1/series-by-country
* https://github.com/cipriancraciun/covid19-datasets/tree/master/exports/ecdc/v1/worldwide-by-country

Would these be helpful for the moment?

**Comment by Dan-74** [comment]
Hi @cipriancraciun that's fine for me. Multsumesc.

**Comment by cipriancraciun** [comment]
I'll think about adding a web-based UI for querying these datasets, but that would be a little bit more involved.

**Comment by cipriancraciun** [comment]
As described in #33 I've added some speradsheet-like HTML pages like for example:
* https://scratchpad.volution.ro/ciprian/eedf5eb117ec363ca4f88492b48dbcd3/exports/ecdc/v1/worldwide/values.html

It allows the user to filter, sort and copy-paste the data.  (Not all columns are showed, only confirmed and deaths.)

**Comment by Dan-74** [comment]
Great job. Is it auto-update with new data?

**Comment by cipriancraciun** [comment]
@Dan-74 yes, I update all these files a couple of times a day, but each dataset is usually updated upstream once a day.

(You can look in the commits in this repo for a clue when the data was updated.)
