### ISSUE TITLE
Used by jojo4u/covid-19-graphs-jo and thanks!

### ISSUE THREAD

**Issue by jojo4u** [cipriancraciun/covid19-datasets#35]
I'm using your derived data in my little python graph project. It shows cumulative and daily cases/deaths per capita since in the beginning everybody only reported absolute data. If you're interested you can add https://github.com/jojo4u/covid-19-graphs-jo to the "Used By" section of your readme (I figured a pull request would be a bit overkill for such a small change).

I want to give you a big "thank you" for your effort to consolidate and augment the CSSE data. At first I used https://github.com/datasets/covid-19/ but since the infamous data change at CSSE it missed US state data. Your jhu/daily data includes it and also has population :)

**Comment by cipriancraciun** [comment]
Thanks for providing the link.  I've included it in the readme section.

If you encounter any issues with the dataset, or have any ideas, don't hesitate to open an issue her.
