### ISSUE TITLE
JHU dataset doesn't contain the last day data

### ISSUE THREAD

**Issue by bogdanyan** [cipriancraciun/covid19-datasets#37]
Hi,
There is 2020-04-23 as the last date in jhu dataset, at the same time JHU provides the data about 2020-04-24 at its GitHub and website 
Please, do force data update/fix updating schedule 
Thank you

**Comment by rafaelsabino** [comment]
Truth. I also noticed this today in my graphics. @cipriancraciun Would there be a way to leave these updates automatic? I don't know exactly how you do the daily update. But I remember you saying that the update is manual. There is no way to leave it automatically? Best regards

**Comment by cipriancraciun** [comment]
@bogdanvso @rafaelsabino This morning at 7AM (Romania time) when I tried to run the updates, the JHU daily data set was not published yet.

I'm now running the updates.

----

@rafaelsabino as said earlier, running them automatically is problematic due to many exceptions I have to code in to fix the JHU locations into proper places.

(For example in the last few days, they've introduced the military and prison system as new provinces.)

**Comment by cipriancraciun** [comment]
@bogdanvso @rafaelsabino the new datasets have been pushed.

Sorry for the delay.  (Please do not hesitate to open other issues if this happens again.)

**Comment by rafaelsabino** [comment]
Good Morning. They haven't been updated again. It does not appear on the 26th. Could you please reprocess?

**Comment by cipriancraciun** [comment]
@rafaelsabino I did push them 4 hours ago.  Checking the `./exports/jhu/v1/daily/values.tsv` it does appear to have values for the 26th.

Thus perhaps the data is actually missing from the original JHU datasets.

Could you be more specific as to which country / region you are missing the data?

**Comment by rafaelsabino** [comment]
Hello @cipriancraciun, how are you? In fact it is in the general context, no data is brought from the 26th.
![Anotação 2020-04-27 074551](https://user-images.githubusercontent.com/12975702/80363886-45a40500-885b-11ea-9c0b-3b5f38e66364.png)

**Comment by cipriancraciun** [comment]
@rafaelsabino I've just double checked the SQLite for the combined dataset and there are values in there.

Could you double check on your end if perhaps something in the import on your side didn't work?

Also please tell me which exact file you are using to check that one on my side.

**Comment by rafaelsabino** [comment]
Ah really. I just checked your file and the update is there. I did not understand. I always look for the cron update 2h after you do the update and this time I downloaded an outdated file. I did not understand. But I will solve this problem from here. Thanks for informing.
👍 :D

**Comment by cipriancraciun** [comment]
@rafaelsabino today I did the update a little bit later, which might be the cause.

Thus I would suggest you implement  one of the following:
* do the imports once every 6 hours;
* if after the download on your side the file didn't change (for example you can use `cmp -q ./old ./new`, or an MD5), then fail with a warning or retry from 30 to 30 minutes;

**Comment by rafaelsabino** [comment]
Great @cipriancraciun. You are the best. Thank you for your help.
