### ISSUE TITLE
Used by bogdanvso / diseases_risk_analysing and thanks 

### ISSUE THREAD

**Issue by bogdanyan** [cipriancraciun/covid19-datasets#38]
I'm using your derived data for one my personal pet-project (www.covid-info.live). It provides world/country statistics, top-3 by major metrics, some basic analytics related to medical  resources situation (e.g. correlation between number of beds in hospitals and Case fatality rate) and calculates approximate risk to be infected and to die in a given country relatively to a person age/comorbid diseases/medical environment.

I've added your repo link to the site's disclaimer and into my repo
Thank you for your work!

**Comment by cipriancraciun** [comment]
Thanks, I've added a link to your repository in the `readme.md`.
