### ISSUE TITLE
Populate per100k in US County-level data

### ISSUE THREAD

**Issue by jgoerzen** [cipriancraciun/covid19-datasets#40]
Hi,

First, thank you for what you are doing.  I was about to start something similar and then realized it's already been done!  Fantastic!

For the US county-level data in NYT and JHU, the per-100k fields are NULL.

Over at https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv, this population data can be found at the county level.  The FIPS code would be a suitable primary key for cross-referencing into it.

Thanks!

**Comment by cipriancraciun** [comment]
First of all thank you for your interest!

Now regarding the per US-county level statistics, initially my main focus for the COVID19 dataset was the situation in Europe (where I live), plus at that time the only data that was available was at country level.  Then JHU and NYTimes started adding the data at US state level and US county level.  Although the data for US at state level had almost the same quality as the country one, the per US-county data was quite sparse and unreliable, thus I didn't focus on that.

My initial attempt to normalize the US-county level data was to create a mapping file to normalize the county names, as seen in this file:
https://github.com/cipriancraciun/covid19-datasets/blob/master/sources/facts-files/us-locations.ods

However for some reason the US FIPS data (from the official `.gov` site) was blocked from outside US (or perhaps from inside EU), and thus I tried my best to use the Wikipedia pages to get at least the names right.  (But gave up on any further tries.)

Regarding the lookup-table pointed out, given that I merge both JHU and NYTimes data, I would have preferred a third party data source for the population (and area and location if possible).

Thus if you can help me identify a suitable dataset for this additional data I could try to integrate it.

----

That being said, given that my focus is on the "global" scale, thus not US, I've take the decision to map non-continental dependencies as individual countries.  For example Virgin Islands, Puerto Rico, French & Dutch & Holand & China's dependencies.

Thus for those US dependencies, I've also merged all country-level data, and at this moment I don't think I'll revert this.
