### ISSUE TITLE
Sqlite3 schema suggestions

### ISSUE THREAD

**Issue by jgoerzen** [cipriancraciun/covid19-datasets#41]
Hi,

There are a few schema suggestions I would like to make.

1) When the values in the absolute_* and delta_* columns are zero, put a zero there rather than a NULL.  Both columns should be defined NOT NULL in the schema.

2) Removing the FIPS codes from the county-related rows makes it more difficult to cross-reference with other sources.  It would be great to have those still present, or a separate locations table that could be cross-referenced using the location_key to look it up.

3) A more relational model could be useful; for instance, there wouldn't necessarily be a reason to duplicate all the factbook entries on every row when they could be correlated with a separate factbook table at select time.

On another topic, there doesn't appear to be a row for every day in the table, although this is present in the source material.  It appears rows are omitted when all of the delta_* values would be zero.  Although that reduces storage space, it makes it substantially more difficult to perform analyses using `WHERE date =` type of clauses.  For instance, creating a sum of cases over a set of counties or something would normally be possible using a SELECT but couldn't be done here, since the rows are omitted.

**Comment by cipriancraciun** [comment]
Herein are multiple issues, and I'll take them one-by-one:

> When the values in the absolute_* and delta_* columns are zero, put a zero there rather than a NULL. Both columns should be defined NOT NULL in the schema.
> [...]
> On another topic, there doesn't appear to be a row for every day in the table, although this is present in the source material. It appears rows are omitted when all of the delta_* values would be zero. Although that reduces storage space, it makes it substantially more difficult to perform analyses using WHERE date = type of clauses. For instance, creating a sum of cases over a set of counties or something would normally be possible using a SELECT but couldn't be done here, since the rows are omitted.

The fact that we have `NULL` values, and the fact that some dates don't exist when all deltas are zero, are not an oversight, but a "feature".  :)

Think about the following situation:
* say in day+1 a country reports a total of 10101 cases so far;  then on day+2 it still reports 10101 total cases;  thus the delta is 0;
* say the say country reports in day+1 a total of 10101 cases;  but on day+2 it reports nothing (i.e. no official statement is made, no datapoint is created for that day), but then on day+3 it reports 10102 cases;  what is the delta for day 2 and 3?  my assumption is that for day 2 we have no delta (thus `NULL`), and for day 3 we have 1;
* however going back to the first situation, given that many countries have tens of thousands of cases, is it likely that there is really a zero number of new cases (or deaths or recoveries) in a given day?

Therefore, given that deltas are important in deciding the direction the current situation takes, and the fact that a true zero delta is highly unlikely, I've taken the two decisions you've observed:
* all delta values that are `0` are replaced with a NULL, based on the fact that we don't truly know, and its highly unlikely, that we have a "true" zero report, and thus we transform it into a "we don't know" marker;
* also given that no new cases and no deaths and no recoveries is also highly unlikely (unless the situation was overcome for that country), I have decided to remove all lines that don't change the situation (i.e. all zero deltas implies no row);  also by not repeating the same data over-and-over, we can easily identify when the situation ended for a certain country.

To conclude:  my decision was based on this principle:  I shouldn't "make-up-data" where there is high uncertainty that there is any.  I prefer to let the user (the researcher) to decide how to fill in the gaps.

Regarding the `WHERE date` clauses, you can do a `LEFT JOIN` between a generated dates table (or `SELECT x in VALUES ('date-1', 'date-2', etc.)`) and thus you have your table that contains all dates.

Regarding the aggregate functions (`SUM`, `AVG`, etc.) they shouldn't be impacted by the `NULL` values.

**Therefore with regard the `NULL` values and the missing rows, I don't think a change should be made, without introducing "made-up-data".**

----

> Removing the FIPS codes from the county-related rows makes it more difficult to cross-reference with other sources. It would be great to have those still present, or a separate locations table that could be cross-referenced using the location_key to look it up.

I'll add the FIPS code as `administrative_code` somewhere in the weekend.

----

> A more relational model could be useful; for instance, there wouldn't necessarily be a reason to duplicate all the factbook entries on every row when they could be correlated with a separate factbook table at select time.

Although I agree that normalization is useful in general, when it comes to analytics databases (which this dataset tries to provide), denormalization is actually helpful:
* first it simplifies queries by having all columns "pre-JOINed", thus anyone with simple SQL knowledge (that for example isn't well versed in `JOIN`s) could use this database;
* then it also provides "feature" (population or continent for example) attributes that can easily be filtered upon in simple queries;

**As such if it would really help you, I could create a second normalized SQL script that provides more tables.**
